[tool.setuptools]
packages = ["loupy"]

[project]
# Basic project metadata
name = "loupy"
version = "0.1.1"
description = ""
authors = [
    { name = "lutrarutra", email = "lutrarutra@pm.me" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
loupy = "loupy.cli:main"

[tool.setuptools.package-data]
loupy = ["loupy.R"]