[tool.setuptools]
packages = ["loupy"]

[project]
# Basic project metadata
name = "loupy"
version = "0.1.0"
description = ""
authors = [
    { name = "Artur Gynter", email = "artur.gynter@proton.me" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
loupy = "loupy.cli:main"