package:
    name: loupy
    version: 0.1.1

source:
    path: ..

build:
    noarch: python
    script: python -m pip install --no-deps .
  
requirements:
    build:
        - python
        - setuptools
    run:
        - conda-forge::python>=3.10
        - conda-forge::numpy>=2
        - conda-forge::pandas>=2.2.2
        - conda-forge::anndata
        - conda-forge::r-base>=4.3
        - conda-forge::rpy2
        - conda-forge::r-seurat
        - conda-forge::r-seuratobject
        - conda-forge::r-hdf5r
        - bioconda::r-seurat-data
        - bioconda::r-seurat-disk
        - bioconda::bioconductor-rhdf5


about:
    home: https://github.com/lutrarutra/loupy
    license: MIT
    summary: "Export clusters, annotations and projections from ScanPy's AnnData object to Loupe Cell Browser's .cloupe file format."
